# Generated by Django 6.0 on 2025-12-12 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_perfilcliente_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilcliente',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
