# Generated by Django 6.0 on 2025-12-07 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluguel',
            old_name='valor',
            new_name='valor_total',
        ),
    ]
